openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: OpenAPI MERN Learn Server
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
paths:
  /posts:
    get:
      tags:
        - post
      summary: Returns a list of posts.
      description: ''
      operationId: getPosts
      responses:
        '200':
          description:  A JSON array of posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
components:
  schemas:
    post:
      title: Post title
      message: Post message
      creator: Post creator
      tag: Post tags
      selectedFile: Post image
      likeCount: Post likes
      createdAt: Post created date
      type: object
